version: "2"
run:
  tests: false
linters:
  default: standard
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: "ST1001" # go-jet makes use of dot notion imports

      - path: test\/.+\.go
        linters:
          - errcheck
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
