x-app: &app
  build:
    context: .
  env_file:
    - .env.test

services:
  db:
    restart: always
    image: postgres:16.4
    user: postgres
    env_file:
      - .env.test
    environment:
      POSTGRES_PASSWORD: password
      PG_USER: postgres
      POSTGRES_DB: ezsplit_test
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 5

  app:
    <<: *app
    # entrypoint commands takes precedence over command
    entrypoint: ./entrypoint_test.sh
    command: >
        sh -c "atlas schema apply --env local --auto-approve &&
        gotestsum -- -p=1 ./..."
    volumes:
      - .:/app
    environment:
      GO_ENV: "test"
      # use github-actions format when debugging
      GOTESTSUM_FORMAT: "dots-v2"
    depends_on:
      db:
        condition: service_healthy
