version: '3'

x-app: &app
  build:
    context: .
  env_file:
    - .env

services:
  database:
    restart: always
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "ezsplit_dev"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  pgweb:
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/ezsplit_dev?sslmode=disable
    depends_on:
      - database

  web:
    <<: *app
    command: go run ./cmd/ezsplit/main.go
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
    ports:
      - "7777:7777"
    depends_on:
      - database

  dev-cli:
    <<: *app
    command: bash
    volumes:
      - .:/app
    profiles:
      - dev-cli

