version: '3'

dotenv: [.env]

env:
  ENV: local

tasks:
  apply:db:schema:
    cmds:
      - docker compose exec web atlas schema apply --env local
  
  down:
    cmds:
      - docker compose down
      - pgrep -f 'docker-compose compose watch' | xargs kill -SIGINT
  
  up:
    desc: Runs the application in development mode in docker
    cmds:
      - docker compose watch
  
  generate:graphql:schema:
    cmds:
      - docker compose run --rm dev-cli go run github.com/99designs/gqlgen generate

  logs:
    desc: Tails the logs of the application
    cmds:
      - docker compose logs -f

  compose:
    desc: Acts as a proxy for `docker compose` command
    cmds:
      - docker compose {{.CLI_ARGS}}

  list:
    desc: Lists all available tasks
    cmds:
      - task --list-all
