// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddItemToReceiptInput struct {
	ReceiptID string   `json:"receiptId"`
	Name      string   `json:"name"`
	Price     *float64 `json:"price,omitempty"`
}

type AssignOrDeleteMeToItemInput struct {
	ItemID string `json:"itemId"`
}

type AssignUserToItemInput struct {
	ItemID string `json:"itemId"`
	UserID string `json:"userId"`
}

type DeleteItemPayload struct {
	Msg string `json:"msg"`
	ID  string `json:"id"`
}

type Me struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type Mutation struct {
}

type Query struct {
}

type ReceiptInput struct {
	Description string   `json:"description"`
	Price       *float64 `json:"price,omitempty"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type UserInput struct {
	Username string `json:"username"`
}

type UserWithJwt struct {
	ID          string `json:"id"`
	Username    string `json:"username"`
	AccessToken string `json:"accessToken"`
}
