name: golangci-lint
on: [push]

env:
  GO_VERSION: 1.24.2

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.2

      - name: Go Vet
        run: go vet ./...

  test-gqlgen-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: GQLGen Generate test
        run: go tool github.com/99designs/gqlgen generate
