name: Add label on Pull Request
on:
  pull_request:
    types: [opened]

env:
  USERS: '["carlqt", "jawt94"]'

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add LABEL
        if: ${{ contains(env.USERS, github.actor) }}
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${{ github.token }}' \
          -d '{"labels": ["se", "invalid"]}'
